name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    name: Smoke (import + offline nowcast)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip & install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          # Optional tools used by some installs
          pip install pytest

      - name: Show environment
        run: |
          python -c "import sys,platform; print('Python', sys.version); print('OS', platform.platform())"
          pip list

      - name: Import sanity
        run: |
          python - <<'PY'
          import autoregime
          print("autoregime version OK")
          from autoregime.engines import hmm_sticky
          print("HMM engine import OK")
          try:
              from autoregime.engines import bocpd
              print("BOCPD engine import OK")
          except Exception as e:
              raise SystemExit(f"BOCPD import failed: {e}")
          PY

      - name: Run offline smoke test
        run: |
          python -m script.ci_smoke