name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    name: Smoke (import + offline nowcast)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          # Install your package and lightweight dev tools
          pip install -e .
          pip install pytest

      - name: Run offline smoke test
        run: |
          python -m script.ci_smoke