name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Avoid piling up parallel runs on the same branch
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  smoke:
    name: Smoke (import + tiny nowcast)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # If you have requirements.txt, install it first
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install your package editable (ok if already installed)
          pip install -e . || true

      # If you created scripts/ci_smoke.py, use it; otherwise we run an inline smoke.
      - name: Run smoke test
        run: |
          if [ -f scripts/ci_smoke.py ]; then
            python scripts/ci_smoke.py
          else
            python - <<'PY'
            import autoregime as ar
            tickers = ["SPY","UUP"]          # light & reliable
            methods = ["hmm","bocpd"]        # test both engines

            for m in methods:
                for t in tickers:
                    try:
                        txt = ar.stable_report(t, start_date="2019-01-01", method=m)
                        print(f"\n=== {m.upper()} — {t} ===")
                        print(txt[:400])
                    except Exception as e:
                        print(f"\n=== {m.upper()} — {t} === ERROR:", e)
            PY

  # Optional quality job (non-blocking). It won’t fail your CI.
  quality:
    name: Lint & typecheck (non-blocking)
    runs-on: ubuntu-latest
    needs: smoke
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
      - name: Ruff
        run: ruff check autoregime || true
      - name: Mypy
        run: mypy --ignore-missing-imports autoregime || true