name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Smoke (import + tiny nowcast)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AR_SMOKE_REAL: "0"   # keep network optional; flip to "1" to probe Yahoo/FRED
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Upgrade pip & install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install -e .

      - name: Show pip freeze (debug)
        run: pip freeze

      - name: Run smoke script
        run: python scripts/ci_smoke.py