name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    name: Smoke (import + tiny nowcast)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install --upgrade pip
          # Install the package + runtime deps (no dev tools needed for smoke)
          pip install -e .
          # Ensure core deps present (belt & suspenders)
          pip install numpy pandas hmmlearn scikit-learn yfinance pandas_datareader

      - name: Run offline smoke test
        env:
          AUTOREGIME_CI: "1"   # engines can read this if needed
        run: |
          python scripts/ci_smoke.py