name: CI
on:
  push: {branches: [ main ]}
  pull_request: {branches: [ main ]}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      # Don't fail the build on lint for now (we’ll tighten later)
      - name: Lint (Ruff)
        run: ruff check autoregime || echo "ruff failed (non-blocking for now)"

      - name: Typecheck (Mypy)
        run: mypy --config-file mypy.ini autoregime || echo "mypy failed (non-blocking for now)"

      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings